apiVersion: v1
kind: ConfigMap
metadata:
  name: cosmos-config
  namespace: cosmos
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  NEXT_PUBLIC_GATEWAY_URL: "/api/v1"
  COSMOS_OTEL_ENABLED: "false"
